# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-04 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Female',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d')),
                ('fname', models.CharField(max_length=32, verbose_name=b'\xe6\xb3\x95\xe5\x90\x8d')),
                ('gender', models.CharField(max_length=10, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab')),
                ('race', models.CharField(max_length=20, verbose_name=b'\xe6\xb0\x91\xe6\x97\x8f')),
                ('degree', models.CharField(max_length=32, verbose_name=b'\xe5\xad\xa6\xe5\x8e\x86')),
                ('guiyi_year', models.CharField(max_length=32, verbose_name=b'\xe7\x9a\x88\xe4\xbe\x9d\xe5\xb9\xb4\xe4\xbb\xbd')),
                ('guiyi_date', models.CharField(max_length=32, verbose_name=b'\xe7\x9a\x88\xe4\xbe\x9d\xe6\x97\xa5\xe6\x9c\x9f')),
                ('fahui_name', models.CharField(max_length=32, verbose_name=b'\xe6\xb3\x95\xe4\xbc\x9a\xe5\x90\x8d\xe7\xa7\xb0')),
                ('guiyi_code', models.CharField(max_length=32, verbose_name=b'\xe6\xb3\x95\xe4\xbc\x9a\xe5\x90\x8d\xe7\xa7\xb0')),
                ('receipt', models.CharField(max_length=32, verbose_name=b'\xe6\x94\xb6\xe6\x8d\xae\xe5\x8f\xb7')),
                ('personnel_id', models.CharField(max_length=32, verbose_name=b'\xe8\xba\xab\xe4\xbb\xbd\xe8\xaf\x81\xe5\x8f\xb7')),
                ('job', models.CharField(max_length=32, verbose_name=b'\xe8\x81\x8c\xe4\xb8\x9a')),
                ('hobby', models.CharField(max_length=64, verbose_name=b'\xe7\x88\xb1\xe5\xa5\xbd')),
                ('birthday', models.CharField(max_length=32, verbose_name=b'\xe7\x94\x9f\xe6\x97\xa5')),
                ('phone', models.CharField(max_length=20, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7')),
                ('telephone', models.CharField(max_length=20, verbose_name=b'\xe5\x9b\xba\xe5\xae\x9a\xe7\x94\xb5\xe8\xaf\x9d')),
                ('workplace', models.CharField(max_length=64, verbose_name=b'\xe5\xb7\xa5\xe4\xbd\x9c\xe5\x8d\x95\xe4\xbd\x8d')),
                ('province', models.CharField(max_length=64, verbose_name=b'\xe7\x8e\xb0\xe5\xb1\x85\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x88\xe7\x9c\x81)')),
                ('city', models.CharField(max_length=64, verbose_name=b'\xe7\x8e\xb0\xe5\xb1\x85\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x88\xe5\xb8\x82)')),
                ('district', models.CharField(max_length=64, verbose_name=b'\xe7\x8e\xb0\xe5\xb1\x85\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x88\xe5\x8e\xbf)')),
                ('address', models.CharField(max_length=64, verbose_name=b'\xe7\x8e\xb0\xe5\xb1\x85\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x88\xe4\xb9\xa1\xe9\x95\x87/\xe5\xb0\x8f\xe5\x8c\xba/\xe8\xa1\x97\xe9\x81\x93)')),
                ('graduate_school', models.CharField(max_length=64, verbose_name=b'\xe6\xaf\x95\xe4\xb8\x9a\xe5\xad\xa6\xe6\xa0\xa1')),
            ],
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d')),
                ('fname', models.CharField(max_length=32, verbose_name=b'\xe6\xb3\x95\xe5\x90\x8d')),
                ('gender', models.CharField(max_length=10, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab')),
                ('race', models.CharField(max_length=20, verbose_name=b'\xe6\xb0\x91\xe6\x97\x8f')),
                ('degree', models.CharField(max_length=32, verbose_name=b'\xe5\xad\xa6\xe5\x8e\x86')),
                ('guiyi_year', models.CharField(max_length=32, verbose_name=b'\xe7\x9a\x88\xe4\xbe\x9d\xe5\xb9\xb4\xe4\xbb\xbd')),
                ('guiyi_date', models.CharField(max_length=32, verbose_name=b'\xe7\x9a\x88\xe4\xbe\x9d\xe6\x97\xa5\xe6\x9c\x9f')),
                ('fahui_name', models.CharField(max_length=32, verbose_name=b'\xe6\xb3\x95\xe4\xbc\x9a\xe5\x90\x8d\xe7\xa7\xb0')),
                ('guiyi_code', models.CharField(max_length=32, verbose_name=b'\xe6\xb3\x95\xe4\xbc\x9a\xe5\x90\x8d\xe7\xa7\xb0')),
                ('receipt', models.CharField(max_length=32, verbose_name=b'\xe6\x94\xb6\xe6\x8d\xae\xe5\x8f\xb7')),
                ('personnel_id', models.CharField(max_length=32, verbose_name=b'\xe8\xba\xab\xe4\xbb\xbd\xe8\xaf\x81\xe5\x8f\xb7')),
                ('job', models.CharField(max_length=32, verbose_name=b'\xe8\x81\x8c\xe4\xb8\x9a')),
                ('hobby', models.CharField(max_length=64, verbose_name=b'\xe7\x88\xb1\xe5\xa5\xbd')),
                ('birthday', models.CharField(max_length=32, verbose_name=b'\xe7\x94\x9f\xe6\x97\xa5')),
                ('phone', models.CharField(max_length=20, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7')),
                ('telephone', models.CharField(max_length=20, verbose_name=b'\xe5\x9b\xba\xe5\xae\x9a\xe7\x94\xb5\xe8\xaf\x9d')),
                ('workplace', models.CharField(max_length=64, verbose_name=b'\xe5\xb7\xa5\xe4\xbd\x9c\xe5\x8d\x95\xe4\xbd\x8d')),
                ('province', models.CharField(max_length=64, verbose_name=b'\xe7\x8e\xb0\xe5\xb1\x85\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x88\xe7\x9c\x81)')),
                ('city', models.CharField(max_length=64, verbose_name=b'\xe7\x8e\xb0\xe5\xb1\x85\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x88\xe5\xb8\x82)')),
                ('district', models.CharField(max_length=64, verbose_name=b'\xe7\x8e\xb0\xe5\xb1\x85\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x88\xe5\x8e\xbf)')),
                ('address', models.CharField(max_length=64, verbose_name=b'\xe7\x8e\xb0\xe5\xb1\x85\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x88\xe4\xb9\xa1\xe9\x95\x87/\xe5\xb0\x8f\xe5\x8c\xba/\xe8\xa1\x97\xe9\x81\x93)')),
                ('graduate_school', models.CharField(max_length=64, verbose_name=b'\xe6\xaf\x95\xe4\xb8\x9a\xe5\xad\xa6\xe6\xa0\xa1')),
            ],
        ),
        migrations.CreateModel(
            name='Xiaozu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d')),
                ('gender', models.CharField(max_length=10, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab')),
                ('phone_num', models.CharField(max_length=32, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7')),
                ('birthday', models.CharField(max_length=32, verbose_name=b'\xe7\x94\x9f\xe6\x97\xa5')),
                ('address', models.CharField(max_length=128, verbose_name=b'\xe7\x8e\xb0\xe5\xb1\x85\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x88\xe4\xb9\xa1\xe9\x95\x87/\xe5\xb0\x8f\xe5\x8c\xba/\xe8\xa1\x97\xe9\x81\x93)')),
                ('xiaozu_type', models.CharField(max_length=32, verbose_name=b'\xe5\xb0\x8f\xe7\xbb\x84\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('xiaozu_lang', models.CharField(max_length=32, verbose_name=b'\xe5\xb0\x8f\xe7\xbb\x84\xe8\xaf\xad\xe8\xa8\x80\xe7\xa7\x8d\xe7\xb1\xbb')),
                ('xiaozu_dizhi', models.CharField(max_length=128, verbose_name=b'\xe5\xad\xa6\xe4\xbd\x9b\xe5\xb0\x8f\xe7\xbb\x84\xe5\x9c\xb0\xe5\x9d\x80')),
                ('xiaozu_fou', models.CharField(max_length=128, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x8f\x82\xe5\x8a\xa0\xe5\xad\xa6\xe4\xbd\x9b\xe5\xb0\x8f\xe7\xbb\x84')),
            ],
        ),
    ]
